const spellData = [

    {   "spell_id" : 1,
        "spell_name" : "Strength",
        "spell_meaning" : "Courage, Inner Strength, Control",
        "spell_type" : "Honor",
        "spell_damage" : 45,
        "spell_magnification" : 25,
        "spell_skills_it_magnifies" : ["honor", "rage", "survival"],
        "spell_drain_effect" : 0,
        "spell_heal_effect" : 25,
        "spell_description" : "Strength spells yield both courage and physical strength to the benefactor.  Extra 25 point damage if combined with skills of 'honor' or 'rage,' or 'survival'",
        "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
        "spell_asset_back" : "./assets/cards_small/strength_small.jpg",
        "spell_xp" : "Evocation Mastery"
    },
    {
        "spell_id" : 2,
        "spell_name" : "The Tower",
        "spell_meaning" : "Upheaval, chaos, revelation, disruption",
        "spell_type" : "Honor",
        "spell_damage" : 119,
        "spell_magnification" : 25,
        "spell_skills_it_magnifies" : ["chaos", "foolery"],
        "spell_drain_effect" : 18,
        "spell_heal_effect" : 0,
        "spell_description" : "'The Tower' instills chaos wherever it is called.  Extra 25 point damage if combined with skills of 'chaos' or 'foolery.'",
        "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
        "spell_asset_back" : "./assets/cards_small/the_tower_small.jpg",
        "spell_xp" : "Evocation Mastery"
    },
    {
        "spell_id" : 3,
        "spell_name" : "The Hermit",
        "spell_meaning" : "Introspection, Solitude",
        "spell_type" : "Honor",
        "spell_damage" : 25,
        "spell_magnification" : 25,
        "spell_skills_it_magnifies" : ["survical", "magic"],
        "spell_drain_effect" : 48,
        "spell_heal_effect" : 300,
        "spell_description" : "Opposite of chaos, the hermit brings inner peace and introspection unable to be touched by external forces.  Extra 25 point damage if combined with skills of 'survival' or 'magic.'",
        "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
        "spell_asset_back" : "./assets/cards_small/the_hermit_small.jpg",
        "spell_xp" : "Arcane Domain"
    },
    // {
    //     "spell_id" : 4,
    //     "spell_name" : "The Hierophant",
    //     "spell_meaning" : "Tradition, conformity, morality",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 32,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["honor", "infiltration"],
    //     "spell_drain_effect" : 2,
    //     "spell_heal_effect" : 0,
    //     "spell_secondary_weaknesses_which_trigger_effect" : [""],
    //     "spell_description" : "A debased magic used in thievery and priestcraft to instill belief or conformity.  Extra 25 point damage if combined with skills of 'honor' or 'infiltration.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/the_hierophant_small.jpg",
    //     "spell_xp" : "Cantrips"
    // },
    // {
    //     "spell_id" : 5,
    //     "spell_name" : "The Star",
    //     "spell_meaning" : "Hope, Faith, Spirituality",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 0,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["elemental", "strategem"],
    //     "spell_drain_effect" : 5,
    //     "spell_heal_effect" : 150,
    //     "spell_description" : "Inspires subject with hope, faith, renewal.  Extra 25 point damage if combined with skills of 'elemental' or 'strategem.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/the_star_small.jpg",
    //     "spell_xp" : "Intermediate Elemental"
    // },
    // {
    //     "spell_id" : 6,
    //     "spell_name" : "The Fool",
    //     "spell_meaning" : "New Beginnings, Innocence, Spontaneity",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 90,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["foolery", "chaos"],
    //     "spell_drain_effect" : 25,
    //     "spell_heal_effect" : 90,
    //     "spell_description" : "Represents a new beginning, spontaneity.  Increases faith, unfortunately it enhances neither wisdom or knowledge with it.  Extra 25 point damage if combined with skills of 'foolery' or 'chaos,' or 'infiltration'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/the_fool_small.jpg",
    //     "spell_xp" : "Spoken Arcana"
    // },
    // {
    //     "spell_id" : 7,
    //     "spell_name" : "The Moon",
    //     "spell_meaning" : "Illusion, intuition, dreams",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 60,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["elemental", "stealth", "infiltration"],
    //     "spell_drain_effect" : 6,
    //     "spell_heal_effect" : 25,
    //     "spell_description" : "When used with stealh or infiltration, creates an astral projection of oneself.  Can also have healing properties.  Extra 25 point damage if combined with skills of 'elemental', 'stealth,' or 'infiltration.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/the_moon_small.jpg",
    //     "spell_xp" : "Evocation Mastery"
    // },
    // {
    //     "spell_id" : 8,
    //     "spell_name" : "Justice",
    //     "spell_meaning" : "Fairness, Truth, Balance",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 102,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["honor"],
    //     "spell_drain_effect" : 15,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "Justice projects an understanding of truth within the mind of the caster and the bewitched, causing immense discomfort for anyone with evil intentions.  Extra 25 point damage if combined with skills of 'honor.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/justice_small.jpg",
    //     "spell_xp" : "Evocation Mastery"
    // },
    // {
    //     "spell_id" : 9,
    //     "spell_name" : "The Magician",
    //     "spell_meaning" : "Manifestations, Resourcefulness, Power",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 164,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["magic", "chaos"],
    //     "spell_drain_effect" : 41,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "Has the ability to temporarily combine competing realities to create a blended, sometimes controllable outcome.  Extra 25 point damage if combined with skills of 'magic' or 'chaos.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/the_magician_small.jpg",
    //     "spell_xp" : "Arcane Domain"
    // },
    // {
    //     "spell_id" : 10,
    //     "spell_name" : "Wheel of Fortune",
    //     "spell_meaning" : "Cycles, Luck, Fate, Destiny",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 134,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["foolery", "magic"],
    //     "spell_drain_effect" : 27,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "Represents a circle, or cycle, of unpredictable fate.  Extra 25 point damage if combined with skills of 'foolery' or 'magic.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/wheel_of_fortune_small.jpg",
    //     "spell_xp" : "Spoken Arcana"
    // },
    // {
    //     "spell_id" : 11,
    //     "spell_name" : "The Sun",
    //     "spell_meaning" : "Joy, Access, Celebration",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 10,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["honor", "elemental"],
    //     "spell_drain_effect" : 8,
    //     "spell_heal_effect" : 68,
    //     "spell_description" : "To those who have walked the path of peace, it's light brings restorative life.  To the rest a burning consumption.  Extra 25 point damage if combined with skills of 'honor' or 'elemental.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/the_sun_small.jpg",
    //     "spell_xp" : "Intermediate Elemental"
    // },
    // {
    //     "spell_id" : 12,
    //     "spell_name" : "The World",
    //     "spell_meaning" : "Integration, Accomplishment",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 15,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["honor", "foolery"],
    //     "spell_drain_effect" : 1,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "Represents completion.  Either increases subjects resoluteness, or blinds them to the consequences.  Either way, pushing them to decisive action.  Extra 25 point damage if combined with skills of 'honor' or 'rage.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/the_world_small.jpg",
    //     "spell_xp" : "Cantrips"
    // },
    // {
    //     "spell_id" : 13,
    //     "spell_name" : "The Lovers",
    //     "spell_meaning" : "Love, Harmony, Alignment",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 143,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["honor", "foolery", "survival"],
    //     "spell_drain_effect" : 29,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "Unites and enhances any relationship based on love, trust, passion, or fate.  Extra 25 point damage if combined with skills of 'honor' or 'foolery,' or 'survival.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/the_lovers_small.jpg",
    //     "spell_xp" : "Spoken Arcana"
    // },
    // {
    //     "spell_id" : 14,
    //     "spell_name" : "Death",
    //     "spell_meaning" : "Ending, Beginnings, Transformations",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 1000,
    //     "spell_magnification" : 0,
    //     "spell_skills_it_magnifies" : [],
    //     "spell_drain_effect" : 25,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "The vessel of absolution and the ferrier to either judgement or peace.  Known as one of The Cosmic Pair, mastery can only be bestowed by a celestial power.",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/death_small.jpg",
    //     "spell_xp" : "Cosmic"
    // },
    // {
    //     "spell_id" : 15,
    //     "spell_name" : "The High Priestess",
    //     "spell_meaning" : "Intuition, unconcious knowledge, feminity",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 178,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["survival", "femininity"],
    //     "spell_drain_effect" : 45,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "Summons the unconscious knowledge .  Extra 25 point damage if combined with skills of 'honor' or 'rage' or 'femininity'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/high_priestess_small.jpg",
    //     "spell_xp" : "Arcane Domain"
    // },
    // {
    //     "spell_id" : 16,
    //     "spell_name" : "The Emperor",
    //     "spell_meaning" : "Authority, Structure",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 5,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["honor", "rage"],
    //     "spell_drain_effect" : 0,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "The Emperor spell influences all authorities within range to bring their armies to defend the spell caster, unfortunately it usually only influences the honorable or the insane.  Extra 25 point damage if combined with skills of 'honor' or 'rage.'",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/emperor_small.jpg",
    //     "spell_xp" : "Cantrips"
    // },
    // {
    //     "spell_id" : 17,
    //     "spell_name" : "Judgment",
    //     "spell_meaning" : "Judgement, Rebirth, Inner Calling, Absolution",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 1000,
    //     "spell_magnification" : 0,
    //     "spell_skills_it_magnifies" : [],
    //     "spell_drain_effect" : 25,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "Represents total absolution and finality.  Known as one of The Cosmic Pair, mastery can only be bestowed by a celestial power.",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/judgement_small.jpg",
    //     "spell_xp" : "Cosmic"
    // },
    // {
    //     "spell_id" : 18,
    //     "spell_name" : "Empress",
    //     "spell_meaning" : "Motherhood, nurturing, abundance",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 142,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["survival", "femininity", "honor"],
    //     "spell_drain_effect" : 85,
    //     "spell_heal_effect" : 250,
    //     "spell_description" : "Represents fertility, nurturing and abundance. Signifies creation.",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/empress_small.jpg",
    //     "spell_xp" : "Arcane Domain"
    // },
    // {
    //     "spell_id" : 19,
    //     "spell_name" : "The Chariot",
    //     "spell_meaning" : "Control, willpower, and victory",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 125,
    //     "spell_magnification" : 0,
    //     "spell_skills_it_magnifies" : ["elemental", "foolery"],
    //     "spell_drain_effect" : 25,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "The chariot spell brings progression to the casters intentions.",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/the_chariot_small.jpg",
    //     "spell_xp" : "Intermediate Elemental"
    // },
    // {
    //     "spell_id" : 20,
    //     "spell_name" : "Temperance",
    //     "spell_meaning" : "Balance, moderation and harmony",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 50,
    //     "spell_magnification" : 25,
    //     "spell_skills_it_magnifies" : ["chaos"],
    //     "spell_drain_effect" : 100,
    //     "spell_heal_effect" : 50,
    //     "spell_description" : "Temperance finds virtue in positioning itself exactly between evil and goodness, hence this spell deals exactly the same damage to the bearer as the enemy",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/temperance_small.jpg",
    //     "spell_xp" : "Cantrips"

    // },
    // {
    //     "spell_id" : 21,
    //     "spell_name" : "The Hanged Man",
    //     "spell_meaning" : "Letting go, surrender",
    //     "spell_type" : "Honor",
    //     "spell_damage" : 104,
    //     "spell_magnification" : 0,
    //     "spell_skills_it_magnifies" : ["survival", "honor"],
    //     "spell_drain_effect" : 100,
    //     "spell_heal_effect" : 0,
    //     "spell_description" : "While this spell deals moderate damage, the act of surrender deals an exceptional toll on the caster.",
    //     "spell_asset_front" : "./assets/assets/cards_small/front.jpg",
    //     "spell_asset_back" : "./assets/cards_small/hanged_man_small.jpg",
    //     "spell_xp" : "Intermediate Elemental"
    // }
]

export default spellData