const spellData = [
{
    "spell_id" : 1,
    "spell_name" : "Strength",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 2,
    "spell_name" : "The Tower",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 3,
    "spell_name" : "The Hermit",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 4,
    "spell_name" : "The Hierophant",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 5,
    "spell_name" : "The Star",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 6,
    "spell_name" : "The Fool",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 7,
    "spell_name" : "The Moon",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 8,
    "spell_name" : "Justice",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 9,
    "spell_name" : "The Magician",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 10,
    "spell_name" : "Wheel of Fortune",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 11,
    "spell_name" : "The Sun",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 12,
    "spell_name" : "The World",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 13,
    "spell_name" : "The Lovers",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 14,
    "spell_name" : "Death",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 15,
    "spell_name" : "The High Priestess",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 16,
    "spell_name" : "The Emperor",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
{
    "spell_id" : 17,
    "spell_name" : "Judgment",
    "spell_meaning" : "Inner Strength",
    "spell_type" : "Honor",
    "spell_applied_to_hero" : true,
    "spell_primary__when_cast_on_hero" : "Degrades their honor",
    "spell_primary__when_cast_on_villain": "Weakened in the presence of true honor and fidelity",
    "spell_secondary__effect_on_caster_by_strength" : 25,
    "spell_secondary__percentage_when_secondary_strength_takes_effect" : .25,
    "spell_secondary__effect_by_on_caster_by_weakness" : 25,
    "spell_secondary__weaknesses_which_trigger_effect" : [""],
    "spell_baseline" : 50,
    "spell_magnitude_enhancement" : 25,
    "spell_magnitude_classes_that_are_enhanced" : ["honor", "rage"],
    "spell_description_if_hero_casts" : "put description here",
    "spell_description_if_villain_casts" : "put description here",
    "spell_asset_pathway_front" : "",
    "spell_asset_pathway_back" : ""
},
]

export { spellData }